const AditionphasesList = [
  {
    phase: "1",
    minRange: 1,
    maxRange: 10,
    bgColor: "#58cc02",
    borderColor: "#46a302",
    wasComplete: false,
    releasedPhase: true,
  },
  {
    phase: "2",
    minRange: 1,
    maxRange: 15,
    bgColor: "#58cc02",
    borderColor: "#46a302",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "3",
    minRange: 1,
    maxRange: 20,
    bgColor: "#58cc02",
    borderColor: "#46a302",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "4",
    minRange: 1,
    maxRange: 25,
    bgColor: "#58cc02",
    borderColor: "#46a302",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "5",
    minRange: 1,
    maxRange: 30,
    bgColor: "#58cc02",
    borderColor: "#46a302",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "6",
    minRange: 1,
    maxRange: 35,
    bgColor: "#b402cc",
    borderColor: "#9002a3",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "7",
    minRange: 10,
    maxRange: 40,
    bgColor: "#b402cc",
    borderColor: "#9002a3",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "8",
    minRange: 10,
    maxRange: 45,
    bgColor: "#b402cc",
    borderColor: "#9002a3",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "9",
    minRange: 10,
    maxRange: 50,
    bgColor: "#b402cc",
    borderColor: "#9002a3",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "10",
    minRange: 10,
    maxRange: 55,
    bgColor: "#b402cc",
    borderColor: "#9002a3",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "11",
    minRange: 10,
    maxRange: 60,
    bgColor: "#0242cc",
    borderColor: "#0228a3",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "12",
    minRange: 10,
    maxRange: 65,
    bgColor: "#0242cc",
    borderColor: "#0228a3",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "12",
    minRange: 10,
    maxRange: 70,
    bgColor: "#0242cc",
    borderColor: "#0228a3",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "12",
    minRange: 10,
    maxRange: 75,
    bgColor: "#0242cc",
    borderColor: "#0228a3",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "12",
    minRange: 10,
    maxRange: 80,
    bgColor: "#0242cc",
    borderColor: "#0228a3",
    wasComplete: false,
    releasedPhase: false,
  },
];
export default AditionphasesList;
