export const AditionphasesList = [
  {
    phase: "1",
    minRange: 1,
    maxRange: 10,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: true,
  },
  {
    phase: "2",
    minRange: 1,
    maxRange: 15,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "3",
    minRange: 1,
    maxRange: 20,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "4",
    minRange: 1,
    maxRange: 25,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "5",
    minRange: 1,
    maxRange: 30,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "6",
    minRange: 1,
    maxRange: 35,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "7",
    minRange: 10,
    maxRange: 40,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "8",
    minRange: 10,
    maxRange: 45,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "9",
    minRange: 10,
    maxRange: 50,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "10",
    minRange: 10,
    maxRange: 55,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "11",
    minRange: 10,
    maxRange: 60,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "12",
    minRange: 10,
    maxRange: 65,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "12",
    minRange: 10,
    maxRange: 70,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "12",
    minRange: 10,
    maxRange: 75,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "12",
    minRange: 10,
    maxRange: 80,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
];

export const SubtractionphasesList = [
  {
    phase: "1",
    minRange: 1,
    maxRange: 10,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: true,
  },
  {
    phase: "2",
    minRange: 1,
    maxRange: 15,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "3",
    minRange: 1,
    maxRange: 20,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "4",
    minRange: 1,
    maxRange: 25,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "5",
    minRange: 1,
    maxRange: 30,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "6",
    minRange: 1,
    maxRange: 35,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "7",
    minRange: 10,
    maxRange: 40,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "8",
    minRange: 10,
    maxRange: 45,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "9",
    minRange: 10,
    maxRange: 50,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "10",
    minRange: 10,
    maxRange: 55,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "11",
    minRange: 10,
    maxRange: 60,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "12",
    minRange: 10,
    maxRange: 65,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "12",
    minRange: 10,
    maxRange: 70,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "12",
    minRange: 10,
    maxRange: 75,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
  {
    phase: "12",
    minRange: 10,
    maxRange: 80,
    bgColor: "#6E86CC",
    borderColor: "#43517c",
    wasComplete: false,
    releasedPhase: false,
  },
];
